### ISSUE TITLE
Set the max price for a spot request

### ISSUE THREAD

**Issue by marina-manrique** [laughedelic/loquat#9]
It would be good to be able to set the max price for a spot request

**Comment by laughedelic** [comment]
As far as I understand, we can just use [another `PurchaseModel`](https://github.com/ohnosequences/aws-scala-tools/blob/b4884998fa2028d959c782e7ff7a13927f801a20/src/main/scala/ohnosequences/awstools/autoscaling/AutoScalingGroup.scala#L28) from aws-scala-tools. Both in `managerConfig` and in `workersConfig` you can set `purchaseModel = Spot(3.14)` (put there you own price).

**Comment by marina-manrique** [comment]
Cool :+1:
